package HebrewDate;

public enum HebrewHolidayId {
	NONE(0),
	PESACH(1),
	PESACH_VII(3),
	YOM_HASHOAH(5),
	YOM_HAZIKARON(6),
	YOM_HAATZMAUT(7),
	PESACH_SHENI(8),
	LAG_BOMER(9),
	YOM_YERUSHALAYIM(10),
	SHAVUOT(11),
	FAST_OF_TAMMUZ(13),
	FAST_OF_AV(14),
	TU_BAV(15),
	ROSH_HASHANA(16),
	ROSH_HASHANA_II(17),
	TZOM_GEDALIAH(18),
	YOM_KIPPUR(19),
	SUKKOT(20),
	HOSHANA_RABA(22),
	SHEMINI_ATZERET(23),
	SIMCHAT_TORAH(24),
	SIMCHAT_TORAH_SHEMINI_ATZERETH(25),
	CHANUKKA_I(26),
	CHANUKKA_II(27),
	CHANUKKA_III(28),
	CHANUKKA_IV(29),
	CHANUKKA_V(30),
	CHANUKKA_VI(31),
	CHANUKKA_VII(32),
	CHANUKKA_VIII(33),
	FAST_OF_TEVET(34),
	TU_BSHEVAT(35),
	FAST_OF_ESTHER(36),
	PURIM(37),
	SHUSHAN_PURIM(38);

	public final int value;

	HebrewHolidayId(int value) {
		this.value = value;
	}
}
